# add the following to _config.yml file

title: Syed M Kamran
logo: /assets/images/MyImage3.jpeg
description: [Data Scientist]
remote_theme: pages-themes/minimal@v0.2.0

github:
  repository_url: https://www.youtube.com/
  another_url: another value
  is_project_page: false


  name: Apple
  name: Banana
  name: Orange
  name: Mango
  name: Test

fruits:
- name: Apple
- name: Banana
- name: Orange
- name: Mango


 
