# add the following to _config.yml file

title: Syed Muhammad Kamran
logo: /Assets/Images/MyImage.jpg
description: [Data Scientist]
remote_theme: pages-themes/minimal@v0.2.0

github:
  repository_url: https://www.youtube.com/
  another_url: another value
 
