# add the following to _config.yml file

title: Syed M Kamran
logo: /assets/images/MyImage3.jpeg
description: [Data Scientist]
remote_theme: pages-themes/minimal@v0.2.0

github:
  repository_url: https://www.youtube.com/
  another_url: another value
  is_project_page: false

contact_details:
- name: London
- name: syed_mkamran@outlook.com
- name: www.linkedin.com/in/syedmkamran/
- name: +44 744 8601388
- name: +92 334 3137636

fa_icons:
- name: fas fa-map-marker-alt
- name: far fa-envelope
- name: fab fa-linkedin
- name: fas fa-phone

 
