# add the following to _config.yml file

title: Syed M Kamran
logo: /Assets/Images/MyImage3.jpeg
description: [Data Scientist]
remote_theme: pages-themes/minimal@v0.2.0

github:
  repository_url: https://www.youtube.com/
  another_url: another value
 
